language: python
python:
  - "3.3"
  - "3.4"
services:
  - mongodb
install:
  - pip install -r requirements.txt
  - pip install coveralls --use-mirrors
script:
  - nosetests --with-coverage --cover-package=flask_slither
after_success:
  - coveralls
