language: python
python:
  - "2.7"
    #  - "2.6"
    #  - "2.5"
services:
  - mongodb
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - nosetests --with-coverage
after_success:
  - coveralls
